# Generated by Django 5.2.6 on 2026-02-15 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Desa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_desa', models.CharField(max_length=100)),
                ('kecamatan', models.CharField(max_length=100)),
                ('alamat_kantor', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dibuat_oleh', models.ForeignKey(help_text='Admin kecamatan yang membuat akun desa', on_delete=django.db.models.deletion.CASCADE, related_name='desa_dibuat', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='desa', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PengajuanBLT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noSK', models.CharField()),
                ('fileSK', models.FileField(upload_to='SK_BLT/')),
                ('file_hasil_saw', models.FileField(upload_to='saw/')),
                ('jumlah_dana', models.IntegerField()),
                ('perbulan', models.IntegerField()),
                ('jumlah_kpm', models.IntegerField()),
                ('tahap', models.CharField(max_length=20)),
                ('tahun', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('valid', 'Valid'), ('tidak_valid', 'Tidak Valid')], default='pending', max_length=20)),
                ('catatan', models.TextField(blank=True, null=True)),
                ('tanggal_validasi', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('desa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pengajuan', to='ekbang.desa')),
                ('divalidasi_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pengajuan_divalidasi', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('desa', 'Admin Desa'), ('kecamatan', 'Admin Kecamatan')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Warga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nik', models.CharField(max_length=20, unique=True)),
                ('nokk', models.CharField(max_length=25)),
                ('nama', models.CharField(max_length=100)),
                ('nama_ibu_kandung', models.CharField(max_length=100)),
                ('alamat', models.TextField()),
                ('desil_p3ke', models.IntegerField(help_text='Nilai 1–5 berdasarkan desil P3KE')),
                ('kehilangan_pekerjaan', models.IntegerField(help_text='1 = tidak, 5 = ya')),
                ('sakit_kronis', models.IntegerField(help_text='1 = tidak, 5 = ya')),
                ('tidak_pkh', models.IntegerField(help_text='1 = menerima PKH, 5 = tidak menerima')),
                ('lansia_tunggal', models.IntegerField(help_text='1 = tidak, 5 = ya')),
                ('perempuan_kepala', models.IntegerField(help_text='1 = tidak, 5 = ya')),
                ('desa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warga', to='ekbang.desa')),
            ],
        ),
        migrations.CreateModel(
            name='NormalisasiSAW',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desil_p3ke', models.FloatField()),
                ('kehilangan_pekerjaan', models.FloatField()),
                ('sakit_kronis', models.FloatField()),
                ('pkh', models.FloatField()),
                ('lansia_tunggal', models.FloatField()),
                ('perempuan_kepala', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('desa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normalisasi_saw', to='ekbang.desa')),
                ('warga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ekbang.warga')),
            ],
        ),
        migrations.CreateModel(
            name='HasilSAW',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai_preferensi', models.FloatField()),
                ('ranking', models.IntegerField()),
                ('tanggal_proses', models.DateTimeField(auto_now_add=True)),
                ('desa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hasil_saw', to='ekbang.desa')),
                ('warga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ekbang.warga')),
            ],
        ),
    ]
