# Generated by Django 5.2.6 on 2026-02-18 05:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekbang', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warga',
            name='nik',
            field=models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(message='NIK harus terdiri dari 16 digit angka.', regex='^\\d{16}$')], verbose_name='NIK'),
        ),
        migrations.AlterField(
            model_name='warga',
            name='nokk',
            field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='No KK harus terdiri dari 16 digit angka.', regex='^\\d{16}$')], verbose_name='No. Kartu Keluarga'),
        ),
        migrations.AddIndex(
            model_name='warga',
            index=models.Index(fields=['nik'], name='ekbang_warg_nik_37f68e_idx'),
        ),
        migrations.AddIndex(
            model_name='warga',
            index=models.Index(fields=['nokk'], name='ekbang_warg_nokk_8a3401_idx'),
        ),
    ]
