# Generated by Django 5.2.6 on 2026-01-24 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekbang', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NormalisasiSAW',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desil_p3ke', models.FloatField()),
                ('kehilangan_pekerjaan', models.FloatField()),
                ('sakit_kronis', models.FloatField()),
                ('pkh', models.FloatField()),
                ('lansia_tunggal', models.FloatField()),
                ('perempuan_kepala', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('desa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normalisasi_saw', to='ekbang.desa')),
                ('warga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ekbang.warga')),
            ],
        ),
    ]
