# Generated by Django 5.2.6 on 2026-02-18 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekbang', '0002_alter_warga_nik_alter_warga_nokk_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='warga',
            name='ekbang_warg_nokk_8a3401_idx',
        ),
        migrations.RemoveField(
            model_name='warga',
            name='nama_ibu_kandung',
        ),
        migrations.RemoveField(
            model_name='warga',
            name='nokk',
        ),
        migrations.AddField(
            model_name='warga',
            name='jumlah_keluarga_kpm',
            field=models.IntegerField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
