# Generated by Django 6.0.2 on 2026-03-31 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ekbang", "0003_remove_warga_ekbang_warg_nokk_8a3401_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="warga",
            name="jumlah_keluarga_kpm",
            field=models.IntegerField(),
        ),
    ]
