# Generated by Django 5.2.6 on 2026-04-10 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekbang', '0003_remove_warga_ekbang_warg_nokk_8a3401_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KuotaKPM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('desa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kuota_kpm', to='ekbang.desa')),
            ],
        ),
    ]
