# Generated by Django 5.2.6 on 2026-04-10 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ekbang', '0004_alter_warga_jumlah_keluarga_kpm'),
        ('ekbang', '0004_kuotakpm'),
    ]

    operations = [
    ]
