# Generated by Django 5.2.6 on 2026-04-18 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekbang', '0005_merge_20260410_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='hasilsaw',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hasilsaw',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='normalisasisaw',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='normalisasisaw',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
