# Generated by Django 5.2.6 on 2026-04-18 14:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekbang', '0007_alter_pengajuanblt_filesk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengajuanblt',
            name='fileSK',
            field=models.FileField(upload_to='SK_BLT/', validators=[django.core.validators.FileExtensionValidator(['doc', 'docx', 'xls', 'xlsx', 'pdf'])]),
        ),
        migrations.AlterField(
            model_name='pengajuanblt',
            name='file_hasil_saw',
            field=models.FileField(upload_to='saw/', validators=[django.core.validators.FileExtensionValidator(['doc', 'docx', 'xls', 'xlsx', 'pdf'])]),
        ),
    ]
