# Generated by Django 5.2.6 on 2026-05-19 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekbang', '0008_alter_pengajuanblt_filesk_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminKecamatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kecamatan', models.CharField(max_length=100)),
                ('alamat_kantor', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_kecamatan', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Kecamatan',
                'verbose_name_plural': 'Admin Kecamatan',
            },
        ),
    ]
