# Generated by Django 5.2.6 on 2026-05-19 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ekbang', '0009_adminkecamatan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desa',
            name='dibuat_oleh',
        ),
    ]
