# Generated by Django 5.2.6 on 2026-05-19 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekbang', '0010_remove_desa_dibuat_oleh'),
    ]

    operations = [
        migrations.AddField(
            model_name='desa',
            name='dibuat_oleh',
            field=models.ForeignKey(default=1, help_text='Admin kecamatan yang membuat akun desa', on_delete=django.db.models.deletion.CASCADE, related_name='desa_dibuat', to='ekbang.adminkecamatan'),
            preserve_default=False,
        ),
    ]
