# Generated by Django 5.2.6 on 2026-05-19 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ekbang', '0011_desa_dibuat_oleh'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
