# Generated by Django 5.2.6 on 2026-05-19 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekbang', '0012_delete_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pengajuanblt',
            name='jumlah_kpm',
        ),
        migrations.AlterField(
            model_name='pengajuanblt',
            name='noSK',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='KPMPengajuan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking_snapshot', models.IntegerField(help_text='Ranking warga saat pengajuan dibuat, tidak berubah meski SAW dihitung ulang')),
                ('nilai_snapshot', models.FloatField(help_text='Nilai preferensi saat pengajuan dibuat')),
                ('status', models.CharField(choices=[('penerima', 'Penerima'), ('tidak_lolos', 'Tidak Lolos')], max_length=20)),
                ('hasil_saw', models.ForeignKey(help_text='Snapshot HasilSAW saat pengajuan dibuat', on_delete=django.db.models.deletion.PROTECT, to='ekbang.hasilsaw')),
                ('pengajuan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpm_list', to='ekbang.pengajuanblt')),
                ('warga', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kpm_pengajuan', to='ekbang.warga')),
            ],
            options={
                'ordering': ['ranking_snapshot'],
                'unique_together': {('pengajuan', 'warga')},
            },
        ),
    ]
