# Generated by Django 5.2.6 on 2026-05-19 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekbang', '0013_remove_pengajuanblt_jumlah_kpm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengajuanblt',
            name='jumlah_kpm',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pengajuanblt',
            name='noSK',
            field=models.CharField(),
        ),
        migrations.DeleteModel(
            name='KPMPengajuan',
        ),
    ]
