# Generated by Django 5.2.6 on 2026-05-19 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekbang', '0014_pengajuanblt_jumlah_kpm_alter_pengajuanblt_nosk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengajuanblt',
            name='divalidasi_oleh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pengajuan_divalidasi', to='ekbang.adminkecamatan'),
        ),
    ]
