# Generated by Django 5.2.6 on 2026-05-19 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekbang', '0015_alter_pengajuanblt_divalidasi_oleh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengajuanblt',
            name='noSK',
            field=models.CharField(max_length=70),
        ),
    ]
