# Generated by Django 5.2.6 on 2026-05-30 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekbang', '0016_alter_pengajuanblt_nosk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warga',
            name='desil_p3ke',
            field=models.IntegerField(choices=[(1, 'Desil 1 – Sangat Miskin (Prioritas Utama)'), (2, 'Desil 2 – Miskin'), (3, 'Desil 3 – Rentan Miskin'), (4, 'Desil 4 – Hampir Rentan')]),
        ),
        migrations.AlterField(
            model_name='warga',
            name='kehilangan_pekerjaan',
            field=models.IntegerField(choices=[(1, 'Masih Bekerja'), (3, 'Kehilangan sementara'), (5, 'Kehilangan tetap')]),
        ),
        migrations.AlterField(
            model_name='warga',
            name='lansia_tunggal',
            field=models.IntegerField(choices=[(1, 'Bukan lansia tunggal'), (5, 'Lansia tunggal')]),
        ),
        migrations.AlterField(
            model_name='warga',
            name='perempuan_kepala',
            field=models.IntegerField(choices=[(1, 'Bukan'), (5, 'Perempuan kepala keluarga')]),
        ),
        migrations.AlterField(
            model_name='warga',
            name='sakit_kronis',
            field=models.IntegerField(choices=[(1, 'Tidak ada'), (3, 'Sakit kronis ringan'), (5, 'Sakit kronis berat / difabel')]),
        ),
        migrations.AlterField(
            model_name='warga',
            name='tidak_pkh',
            field=models.IntegerField(choices=[(1, 'Menerima PKH'), (5, 'Tidak menerima PKH')]),
        ),
    ]
