# Generated by Django 5.2.6 on 2026-06-27 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekbang', '0017_alter_warga_desil_p3ke_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hasilsaw',
            name='tahap',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hasilsaw',
            name='tahun',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kuotakpm',
            name='tahap',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kuotakpm',
            name='tahun',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='normalisasisaw',
            name='tahap',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='normalisasisaw',
            name='tahun',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kuotakpm',
            name='desa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kuota_kpm', to='ekbang.desa'),
        ),
        migrations.AlterUniqueTogether(
            name='hasilsaw',
            unique_together={('desa', 'warga', 'tahap', 'tahun')},
        ),
        migrations.AlterUniqueTogether(
            name='kuotakpm',
            unique_together={('desa', 'tahap', 'tahun')},
        ),
        migrations.AlterUniqueTogether(
            name='normalisasisaw',
            unique_together={('desa', 'warga', 'tahap', 'tahun')},
        ),
    ]
