# Generated by Django 5.2.6 on 2026-06-27 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekbang', '0018_hasilsaw_tahap_hasilsaw_tahun_kuotakpm_tahap_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='normalisasisaw',
            name='pkh',
        ),
        migrations.RemoveField(
            model_name='warga',
            name='tidak_pkh',
        ),
        migrations.AlterField(
            model_name='warga',
            name='kehilangan_pekerjaan',
            field=models.IntegerField(choices=[(1, 'Kehilangan tetap'), (3, 'Kehilangan sementara'), (5, 'Masih Bekerja')]),
        ),
    ]
