# Generated by Django 5.2.6 on 2026-06-27 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekbang', '0019_remove_normalisasisaw_pkh_remove_warga_tidak_pkh_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hasilsaw',
            name='nama_warga_arsip',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='hasilsaw',
            name='nik_warga_arsip',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AddField(
            model_name='normalisasisaw',
            name='nama_warga_arsip',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='normalisasisaw',
            name='nik_warga_arsip',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='hasilsaw',
            name='warga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ekbang.warga'),
        ),
        migrations.AlterField(
            model_name='normalisasisaw',
            name='warga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ekbang.warga'),
        ),
    ]
