# Generated by Django 5.2.6 on 2026-06-27 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekbang', '0020_hasilsaw_nama_warga_arsip_hasilsaw_nik_warga_arsip_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hasilsaw',
            name='nama_warga_arsip',
        ),
        migrations.RemoveField(
            model_name='hasilsaw',
            name='nik_warga_arsip',
        ),
        migrations.RemoveField(
            model_name='normalisasisaw',
            name='nama_warga_arsip',
        ),
        migrations.RemoveField(
            model_name='normalisasisaw',
            name='nik_warga_arsip',
        ),
        migrations.AddField(
            model_name='warga',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='warga',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
