# Generated by Django 5.2.6 on 2026-07-04 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekbang', '0021_remove_hasilsaw_nama_warga_arsip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hasilsaw',
            name='nama_warga_arsip',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='normalisasisaw',
            name='nama_warga_arsip',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='normalisasisaw',
            name='desil_p3ke',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='normalisasisaw',
            name='kehilangan_pekerjaan',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='normalisasisaw',
            name='lansia_tunggal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='normalisasisaw',
            name='perempuan_kepala',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='normalisasisaw',
            name='sakit_kronis',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='warga',
            name='desil_p3ke',
            field=models.IntegerField(blank=True, choices=[(1, 'Desil 1 – Sangat Miskin (Prioritas Utama)'), (2, 'Desil 2 – Miskin'), (3, 'Desil 3 – Rentan Miskin'), (4, 'Desil 4 – Hampir Rentan')], null=True),
        ),
        migrations.AlterField(
            model_name='warga',
            name='kehilangan_pekerjaan',
            field=models.IntegerField(blank=True, choices=[(1, 'Kehilangan tetap'), (3, 'Kehilangan sementara'), (5, 'Masih Bekerja')], null=True),
        ),
        migrations.AlterField(
            model_name='warga',
            name='lansia_tunggal',
            field=models.IntegerField(blank=True, choices=[(1, 'Bukan lansia tunggal'), (5, 'Lansia tunggal')], null=True),
        ),
        migrations.AlterField(
            model_name='warga',
            name='perempuan_kepala',
            field=models.IntegerField(blank=True, choices=[(1, 'Bukan'), (5, 'Perempuan kepala keluarga')], null=True),
        ),
        migrations.AlterField(
            model_name='warga',
            name='sakit_kronis',
            field=models.IntegerField(blank=True, choices=[(1, 'Tidak ada'), (3, 'Sakit kronis ringan'), (5, 'Sakit kronis berat / difabel')], null=True),
        ),
        migrations.CreateModel(
            name='Kriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.SlugField()),
                ('nama', models.CharField(max_length=100)),
                ('bobot', models.FloatField(default=0)),
                ('tipe', models.CharField(choices=[('benefit', 'Benefit'), ('cost', 'Cost')], default='benefit', max_length=10)),
                ('urutan', models.IntegerField(default=0)),
                ('aktif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('desa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kriteria', to='ekbang.desa')),
            ],
            options={
                'ordering': ['urutan', 'id'],
                'unique_together': {('desa', 'kode')},
            },
        ),
        migrations.CreateModel(
            name='Subkriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('nilai', models.FloatField()),
                ('urutan', models.IntegerField(default=0)),
                ('kriteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subkriteria', to='ekbang.kriteria')),
            ],
            options={
                'ordering': ['urutan', 'id'],
                'unique_together': {('kriteria', 'label')},
            },
        ),
        migrations.CreateModel(
            name='NormalisasiSAWDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai_normalisasi', models.FloatField()),
                ('kriteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_normalisasi', to='ekbang.kriteria')),
                ('normalisasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='ekbang.normalisasisaw')),
            ],
            options={
                'unique_together': {('normalisasi', 'kriteria')},
            },
        ),
        migrations.CreateModel(
            name='WargaNilaiKriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kriteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nilai_warga', to='ekbang.kriteria')),
                ('subkriteria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nilai_warga', to='ekbang.subkriteria')),
                ('warga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nilai_kriteria', to='ekbang.warga')),
            ],
            options={
                'unique_together': {('warga', 'kriteria')},
            },
        ),
    ]
