# Generated by Django 5.2.6 on 2026-07-04 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ekbang', '0022_hasilsaw_nama_warga_arsip_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='normalisasisaw',
            name='desil_p3ke',
        ),
        migrations.RemoveField(
            model_name='normalisasisaw',
            name='kehilangan_pekerjaan',
        ),
        migrations.RemoveField(
            model_name='normalisasisaw',
            name='lansia_tunggal',
        ),
        migrations.RemoveField(
            model_name='normalisasisaw',
            name='perempuan_kepala',
        ),
        migrations.RemoveField(
            model_name='normalisasisaw',
            name='sakit_kronis',
        ),
        migrations.RemoveField(
            model_name='warga',
            name='desil_p3ke',
        ),
        migrations.RemoveField(
            model_name='warga',
            name='kehilangan_pekerjaan',
        ),
        migrations.RemoveField(
            model_name='warga',
            name='lansia_tunggal',
        ),
        migrations.RemoveField(
            model_name='warga',
            name='perempuan_kepala',
        ),
        migrations.RemoveField(
            model_name='warga',
            name='sakit_kronis',
        ),
    ]
