# Generated by Django 5.2.6 on 2026-07-06 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ekbang', '0023_remove_normalisasisaw_desil_p3ke_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WargaNilaiKriteria',
            new_name='penilaianwarga',
        ),
    ]
