# Generated by Django 5.2.6 on 2026-07-06 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekbang', '0024_rename_warganilaikriteria_penilaianwarga'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hasilsaw',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='hasilsaw',
            name='normalisasi',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='hasil', to='ekbang.normalisasisaw'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='hasilsaw',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='hasilsaw',
            name='desa',
        ),
        migrations.RemoveField(
            model_name='hasilsaw',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='hasilsaw',
            name='nama_warga_arsip',
        ),
        migrations.RemoveField(
            model_name='hasilsaw',
            name='tahap',
        ),
        migrations.RemoveField(
            model_name='hasilsaw',
            name='tahun',
        ),
        migrations.RemoveField(
            model_name='hasilsaw',
            name='warga',
        ),
    ]
