# Generated by Django 5.2.6 on 2026-07-06 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekbang', '0025_alter_hasilsaw_unique_together_hasilsaw_normalisasi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hasilsaw',
            name='normalisasi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hasil', to='ekbang.normalisasisaw'),
        ),
    ]
