# Generated by Django 5.2.6 on 2026-07-11 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekbang', '0026_alter_hasilsaw_normalisasi'),
    ]

    operations = [
        migrations.AddField(
            model_name='warga',
            name='no_kk',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
